### ISSUE TITLE
How to run with 384×384 resolution?

### ISSUE THREAD

**Issue by shijxcs** [ChangyaoTian/VL-LTR#12]
Hi, thank you for the wonderful work. I wonder how to train on images with 384×384 resolutions. As far as I know, [openai](https://github.com/openai/CLIP/blob/main/clip/clip.py) has not released CLIP model with 384 resolution. CLIP from [timm](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py), however, does not contain the corresponding text encoder. Is there any other released pretrained CLIP weights?

**Comment by ChangyaoTian** [comment]
you can interpolate the positional embeddings of CLIP and finetune it on 384x384 resolutions
