### ISSUE TITLE
Problem about running eval.sh

### ISSUE THREAD

**Issue by euminds** [ChangyaoTian/VL-LTR#3]
"""
#!/usr/bin/env bash
set -x

export NCCL_LL_THRESHOLD=0

CONFIG=$1
GPUS=$1
CPUS=$[GPUS*2]
PORT=${PORT:-8886}

CONFIG_NAME=${CONFIG##*/}
CONFIG_NAME=${CONFIG_NAME%.*}

OUTPUT_DIR="./checkpoints/eval"
if [ ! -d $OUTPUT_DIR ]; then
    mkdir ${OUTPUT_DIR}
fi

python -u main.py \
    --port=$PORT \
    --num_workers 4 \
    --resume "./checkpoints/${CONFIG_NAME}/checkpoint.pth" \
    --output-dir ${OUTPUT_DIR} \
    --config $CONFIG ${@:3} \
    --eval \
    2>&1 | tee -a ${OUTPUT_DIR}/train.log
"""
I have two A100, so set GPUS is 2. All other settings according to ReadME.md
but I got a problem when running eval.sh
"""
  File "eval.sh", line 4
    export NCCL_LL_THRESHOLD=0
           ^
SyntaxError: invalid syntax

"""

**Comment by ChangyaoTian** [comment]
Did you follow the standard execution cmd 'bash xxx' in README.md?

**Comment by euminds** [comment]
> 

I know what happend. Sorry
